
version: "3.8"

services:
  django:
    container_name: django
    build: 
      context: .
      dockerfile: ./docker/django/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/server
      - static_volume:/server/static 
      - media_volume:/server/media 
    networks:
      - backend 

    depends_on:
      - postgres
      - rabbitmq
  # rabbit mq as message broker 
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"  # RabbitMQ
      - "15672:15672"
    networks:
      - backend 

# celery as separate container 
  celery:
    container_name: celery
    build: 
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: celery -A core worker --loglevel=info
    volumes:
      - ./server:/server
    depends_on:
      - django
      - rabbitmq
    networks:
      - backend 
  # for full text search , logs , analytics 

  postgres:
    container_name: postgres
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - backend 

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  backend:
    driver: bridge
